name: Create Comment

on: [issue_comment]

jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-create-comment@v1
        if: ${{ startsWith(github.event.comment.body, '/hello','/hi') }}
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
          body: |
            Hello, @${{ github.actor }}! Welocme to are organization.
