name: Validating the list of technical steering committee members
on: 
  pull_request_target:
    types: 
      - closed
  push:
    types:
      - closed
    paths:
       - 'TSC_MEMBERS.json'
jobs:
  compare_TSC:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
  steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate list with schema
        uses: actions/github-script@v4
        script: |
             const fs = require('fs').promises;

             const schema = await fs.readFile('Based_data.json', 'utf8');
             const members = await fs.readFile('TSC_MEMBERS.json', 'utf8');

             var valid = Object.toJSON(schema) == Object.toJSON(members);

             if (!valid) {
              core.error(`Validation of members file failed with the following errors:`);
              core.error(validator.errors);
            } else {
              core.info(`TSC members file is valid`);
            }
